In [56]:
import numpy as np

In [57]:
t = np.array([1,2,3,4,5,6,9])

In [58]:
t[0]

1

In [59]:
type(np.array([1,2,3,4,5,6,]))   # nd means any type of dimention ,# in here data position is as a numeric format

numpy.ndarray

type casting

In [60]:
np.array([1,2,3,4,5,"srk",(4+8j)]) #any type of data write in over here # the whole data convert in to the  sring,# there is differirent type of notation(<u64) for diffirent stringt
                                   # available in side numpy

array(['1', '2', '3', '4', '5', 'srk', '(4+8j)'], dtype='<U64')

up casting

In [61]:
np.array([1,2,3,4,1.0,2.4,3.5]) # it is converting all of my data  into the floating point  #1d array

array([1. , 2. , 3. , 4. , 1. , 2.4, 3.5])

In [62]:
# so it is simple meens it is trying to upcast my data autometically so whatever higher of data available my intire data
#it is convert integer to floating point number (by default it is a nature of numpy np array so this is upcasting )
# and in type casting mens string to integer and intiger to string

In [63]:
np.array([[1,3],[2,6]])  # 2d array

array([[1, 3],
       [2, 6]])

In [64]:
np.array([[[1,2],[4,5],[8,2]]])   # 3d array

array([[[1, 2],
        [4, 5],
        [8, 2]]])

In [65]:


np.array([[[1,2],[5,6]],[[5,8],[6,8]]])

array([[[1, 2],
        [5, 6]],

       [[5, 8],
        [6, 8]]])

In [66]:
np.array([4,5,8], ndmin = 3)

array([[[4, 5, 8]]])

In [67]:
np.array([[1,2,3],[1,2,5],[5,8,7]],ndmin = 3 )

array([[[1, 2, 3],
        [1, 2, 5],
        [5, 8, 7]]])

In [68]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [69]:
np.array([1,2,5], dtype = float)

array([1., 2., 5.])

In [70]:
np.array([[[1,2],[4,5,9],[8,2,6]]])

C:\Users\SHAHRU~1\AppData\Local\Temp/ipykernel_10808/3999517120.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[[1,2],[4,5,9],[8,2,6]]])


array([[list([1, 2]), list([4, 5, 9]), list([8, 2, 6])]], dtype=object)

In [71]:
np.array([[[1,2],[4,5,9],[8,2,6]]])

C:\Users\SHAHRU~1\AppData\Local\Temp/ipykernel_10808/3999517120.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[[1,2],[4,5,9],[8,2,6]]])


array([[list([1, 2]), list([4, 5, 9]), list([8, 2, 6])]], dtype=object)

In [72]:
np.array([1,2], ndmin = 30)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [73]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [74]:
np.array([[1,2],[7,8]]) # (0,0)value 1,(0,1)value 2,(1,0)value 7,(1,1)value 8

array([[1, 2],
       [7, 8]])

In [75]:
np.array([(1,2) , (2,4)],dtype = [("a" , '<i2'), ("b", '<i8')])

array([(1, 2), (2, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [76]:
arr=np.array([(1,2) , (4,5)],dtype = [("a",'<i2'), ("b",'<i8')])  #????????????

In [246]:
arr

array([1, 2, 3, 4])

In [258]:
arr = np.array([(1,2) , (2,4)],dtype = [("a" , '<i8'), ("b", '<i8')])

In [79]:
np.array([(1,2) , (6,7)], dtype = [("a",'<i2'),("b",'<i8')])

array([(1, 2), (6, 7)], dtype=[('a', '<i2'), ('b', '<i8')])

In [254]:
arr[0][1]

2

In [259]:
type(arr[0][0])

numpy.int64

In [81]:
arr[0][1]

2

In [252]:
type(arr[0][1])

IndexError: invalid index to scalar variable.

In [83]:
type(arr[1][0])

numpy.int16

In [84]:
type(arr[0][0])

numpy.int16

In [85]:
arr  = np.array([[1,3],[3,4]])

In [86]:
arr = np.array([[1,3],[2,4]])

In [87]:
arr

array([[1, 3],
       [2, 4]])

In [88]:
type(arr)

numpy.ndarray

In [89]:
arr = np.mat([[1,2],[5,6]])  # use only mat and matrix the work is same for make matrix

In [90]:
arr # ?????????????/

matrix([[1, 2],
        [5, 6]])

In [91]:
np.mat([[1,3],[1,4]])

matrix([[1, 3],
        [1, 4]])

In [92]:
l = [1,2,3,5,9,8,7,4,6,3,2,5,]

In [93]:
l = [1,2,5,4,8,65,]

In [94]:
np.array(l)

array([ 1,  2,  5,  4,  8, 65])

In [95]:
np.asarray(l)

array([ 1,  2,  5,  4,  8, 65])

In [260]:
np.asanyarray(mat)  #?????????

matrix([[1, 2],
        [5, 6]])

In [97]:
np.array(l)   # the work is mostly same (array,asarray,asanyarray)

array([ 1,  2,  5,  4,  8, 65])

In [98]:
np.asarray(l)

array([ 1,  2,  5,  4,  8, 65])

In [99]:
np.asanyarray(l)

array([ 1,  2,  5,  4,  8, 65])

In [100]:
mat = np.matrix(arr)

In [101]:
mat

matrix([[1, 2],
        [5, 6]])

In [102]:
np.asarray(mat) # matrix convert in to array

array([[1, 2],
       [5, 6]])

In [103]:
np.asanyarray(mat) # fort of allaw we try to observ  #  matrix not convert ionto array

matrix([[1, 2],
        [5, 6]])

In [104]:
np.asanyarray(mat) # if data is available in any form of arrayy in that case it will not convert matrix is also subset of the aray
# sub class of the array chilas of the array .so matrix is already kind of the data wich is available in any type of the array so it will no do any type of converson

matrix([[1, 2],
        [5, 6]])

In [105]:
issubclass(np.ndarray,np.matrix) # nd array is a parent class

False

In [106]:
issubclass(np.matrix,np.ndarray) # matrix is a subclass 

True

In [107]:
#array are mutable

In [108]:
a = arr # it is called shallow copy

In [109]:
b= np.copy(arr) # it is called deep copy

In [110]:
arr[0][1] = (67, 9)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [111]:
arr

matrix([[1, 2],
        [5, 6]])

In [112]:
# array eliment are mutable i can mutet any kind of data index of a array

In [113]:
arr

matrix([[1, 2],
        [5, 6]])

In [114]:
l = ([1,2],[5,8])  # deep copr>>>>> any change made to a copy of object do not reflecte in the orinal object

In [115]:
import copy

In [116]:
a= copy.deepcopy(l)

In [117]:
a

([1, 2], [5, 8])

In [118]:
a[0][1] =66

In [119]:
a

([1, 66], [5, 8])

In [120]:
a

([1, 66], [5, 8])

In [121]:
l

([1, 2], [5, 8])

In [122]:
l = ([1,8],[7,8])  # shallow copy>>>>>>>> any change made to a copy of object so reflecte in the orginal object

In [123]:
sh = copy.copy(l)

In [124]:
sh

([1, 8], [7, 8])

In [125]:
l[0][0] =80

In [126]:
l

([80, 8], [7, 8])

In [127]:
b = np.copy(arr)

In [128]:
arr[0][0] = 67

In [129]:
arr

matrix([[67, 67],
        [ 5,  6]])

In [130]:
a

([1, 66], [5, 8])

In [131]:
b

array([[1, 2],
       [5, 6]])

In [132]:
arr[-1]

matrix([[5, 6]])

In [133]:
for i in arr:
    print(i)

[[67 67]]
[[5 6]]


In [134]:
type(np.fromfunction(lambda i , j :i==j,(4,4)))

numpy.ndarray

In [135]:
np.fromfunction(lambda i , j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [136]:
np.fromfunction(lambda i , j : i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [137]:
np.fromfunction(lambda i , j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [138]:
np.fromfunction(lambda i , j :i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [139]:
(i*i for i in range(5))

<generator object <genexpr> at 0x00000273DA135820>

In [140]:
[i*i for i in range(5)] #???????

[0, 1, 4, 9, 16]

In [141]:
np.fromfunction(lambda i , j :i/j,(3,3))

C:\Users\SHAHRU~1\AppData\Local\Temp/ipykernel_10808/2281161872.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))
C:\Users\SHAHRU~1\AppData\Local\Temp/ipykernel_10808/2281161872.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [142]:
gen = (i*i for i in range(5))

In [143]:
def test(x):
    yield x 

In [144]:
test(5)

<generator object test at 0x00000273DA135D60>

In [145]:
gen
for i in gen :
    print(i)

0
1
4
9
16


In [146]:
gen

<generator object <genexpr> at 0x00000273DA135C80>

In [147]:
np.fromiter(range(5),dtype = int)

array([0, 1, 2, 3, 4])

In [148]:
np.fromiter(gen,dtype = int) #?????????

array([], dtype=int32)

In [149]:
np.fromstring('1,2,3,5,4,6',sep = "," ,dtype = int)

array([1, 2, 3, 5, 4, 6])

In [150]:
np.fromstring("1,2,3,4,5", sep = ",", dtype = "int")

array([1, 2, 3, 4, 5])

In [151]:
np.fromstring("210 646 1324 524564", sep = " ",dtype = complex)

array([2.10000e+02+0.j, 6.46000e+02+0.j, 1.32400e+03+0.j, 5.24564e+05+0.j])

In [152]:
arr = np.array([[1,2,5],[2,3,6],[5,6,8]])
arr

array([[1, 2, 5],
       [2, 3, 6],
       [5, 6, 8]])

In [153]:
type(arr)

numpy.ndarray

In [154]:
arr.ndim # given the dimention

2

In [155]:
arr.size

9

In [156]:
arr.shape

(3, 3)

In [157]:
a = np.array([[[1,2,3,4],[5,4,7,8],[2,3,1,5],[4,6,8,7]]])
a

array([[[1, 2, 3, 4],
        [5, 4, 7, 8],
        [2, 3, 1, 5],
        [4, 6, 8, 7]]])

In [158]:
b = np.array([[[1,2,3,4],[1,5,9,7]],[[4,5,8,7],[8,6,1,4]]])
b

array([[[1, 2, 3, 4],
        [1, 5, 9, 7]],

       [[4, 5, 8, 7],
        [8, 6, 1, 4]]])

In [159]:
b.ndim

3

In [160]:
b.size

16

In [161]:
b.shape

(2, 2, 4)

In [162]:
c = np.array([[[1,5,6,9],[6,3,5,2]],[[5,4,2,1],[6,8,9,4]],[[5,6,7,4],[3,9,2,4]],[[8,6,9,4],[7,3,4,9]]])
c

array([[[1, 5, 6, 9],
        [6, 3, 5, 2]],

       [[5, 4, 2, 1],
        [6, 8, 9, 4]],

       [[5, 6, 7, 4],
        [3, 9, 2, 4]],

       [[8, 6, 9, 4],
        [7, 3, 4, 9]]])

In [163]:
c.ndim

3

In [164]:
c.shape

(4, 2, 4)

In [165]:
c.size

32

In [166]:
l = (range(5,6,4)) # range function always get int not a floating num,ber

In [167]:
l

range(5, 6, 4)

In [168]:
l = (range(5.0,5.8,64.0))

TypeError: 'float' object cannot be interpreted as an integer

In [169]:
l = (arange(6.2,9.6,7.5))

NameError: name 'arange' is not defined

In [170]:
list=(range(1,2,5)) # range only accept 3 argument


In [171]:
np.arange(4.6,9.8,7.6) #??????????

array([4.6])

In [172]:
np.arange(6.6)  # so arange accepted float point

array([0., 1., 2., 3., 4., 5., 6.])

In [173]:
np.arange(6.6,9,.3) #start from 6 and gaping between .3, and go in last lenth 9

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [174]:
np.arange(6.6,9,-.3)

array([], dtype=float64)

In [175]:
np.arange(9.,6.6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [176]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [177]:
np.linspace(1,3)

array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

In [178]:
np.linspace(1,8)

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ,
       3.14285714, 3.28571429, 3.42857143, 3.57142857, 3.71428571,
       3.85714286, 4.        , 4.14285714, 4.28571429, 4.42857143,
       4.57142857, 4.71428571, 4.85714286, 5.        , 5.14285714,
       5.28571429, 5.42857143, 5.57142857, 5.71428571, 5.85714286,
       6.        , 6.14285714, 6.28571429, 6.42857143, 6.57142857,
       6.71428571, 6.85714286, 7.        , 7.14285714, 7.28571429,
       7.42857143, 7.57142857, 7.71428571, 7.85714286, 8.        ])

In [179]:
np.linspace(1,5,3) #?????????

array([1., 3., 5.])

In [180]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [181]:
np.empty((3,4))   # random data generate  #?????????

array([[1.33228185e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.06810811e-306, 1.36989084e-071, 9.05832847e-043,
        2.74086197e-057],
       [3.83623702e+175, 4.23027737e+175, 1.34001164e-075,
        5.10743569e-038]])

In [182]:
np.eye(5) # this is identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [183]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [184]:
np.linspace(2,4,4, endpoint = False,axis = 0)

array([2. , 2.5, 3. , 3.5])

In [185]:
np.linspace([1,6],4, endpoint = False , axis = 1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [186]:
np.linspace([1,6],4, endpoint = False , axis = 0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [187]:
np.logspace(2,4,5)

array([  100.        ,   316.22776602,  1000.        ,  3162.27766017,
       10000.        ])

In [188]:
np.logspace([2],[3],axis = 1) # the value of 2 means 2 zero (2d data) and last number in 3 means 3 zero (3d data)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [189]:
d = np.linspace(1,4,20)
d

array([1.        , 1.15789474, 1.31578947, 1.47368421, 1.63157895,
       1.78947368, 1.94736842, 2.10526316, 2.26315789, 2.42105263,
       2.57894737, 2.73684211, 2.89473684, 3.05263158, 3.21052632,
       3.36842105, 3.52631579, 3.68421053, 3.84210526, 4.        ])

In [190]:
d.reshape(1,4,10)

ValueError: cannot reshape array of size 20 into shape (1,4,10)

In [191]:
np.linspace([2,3],20, axis = 0)

array([[ 2.        ,  3.        ],
       [ 2.36734694,  3.34693878],
       [ 2.73469388,  3.69387755],
       [ 3.10204082,  4.04081633],
       [ 3.46938776,  4.3877551 ],
       [ 3.83673469,  4.73469388],
       [ 4.20408163,  5.08163265],
       [ 4.57142857,  5.42857143],
       [ 4.93877551,  5.7755102 ],
       [ 5.30612245,  6.12244898],
       [ 5.67346939,  6.46938776],
       [ 6.04081633,  6.81632653],
       [ 6.40816327,  7.16326531],
       [ 6.7755102 ,  7.51020408],
       [ 7.14285714,  7.85714286],
       [ 7.51020408,  8.20408163],
       [ 7.87755102,  8.55102041],
       [ 8.24489796,  8.89795918],
       [ 8.6122449 ,  9.24489796],
       [ 8.97959184,  9.59183673],
       [ 9.34693878,  9.93877551],
       [ 9.71428571, 10.28571429],
       [10.08163265, 10.63265306],
       [10.44897959, 10.97959184],
       [10.81632653, 11.32653061],
       [11.18367347, 11.67346939],
       [11.55102041, 12.02040816],
       [11.91836735, 12.36734694],
       [12.28571429,

In [192]:
np.logspace([2],[3], axis =1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [193]:
d=np.linspace(4,7,40)
d#  in 40 data produse in between 4 and 7

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [194]:
# let suppose get data in different shape and size
d.ndim

1

In [195]:
d.shape

(40,)

In [196]:
d.size

40

In [197]:
d.reshape(4,7,20)

ValueError: cannot reshape array of size 40 into shape (4,7,20)

In [198]:
# let suppose change data set use transe pose
d.reshape(40,1)  # 40 row and 1 = column and , given 2d over here

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [199]:
# now change in 3d
d.reshape(1,2,20)   # 1 matrix

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [200]:
d=np.linspace(4,7,10)
d#  in 40 data produse in between 4 and 7

array([4.        , 4.33333333, 4.66666667, 5.        , 5.33333333,
       5.66666667, 6.        , 6.33333333, 6.66666667, 7.        ])

In [201]:
d.reshape(1,2,10)  # 2 matrix

ValueError: cannot reshape array of size 10 into shape (1,2,10)

In [202]:
np.logspace(1,3,5)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [203]:
np.random.rand(3) # it is create 3 random data,and whatever random data is gong to create gosian distribution

array([0.465286  , 0.03740022, 0.70614297])

In [204]:
np.random.randn(5) # return data standard normal distribution ,standard normal distribution >>>mean = 0, standard = 1

array([ 2.14112084, -0.6195709 , -0.94620281,  0.20830622,  2.23718045])

In [205]:
np.random.randn(2,5)

array([[-1.31011128, -0.34559481,  1.4591074 , -0.28816706,  0.85387427],
       [-0.40003845,  0.16226766, -0.55039966, -1.5112331 , -1.59933269]])

In [206]:
np.random.randint(1,4)

3

In [207]:
np.random.randint(5,60,(4,4)) 

array([[13, 48, 45, 18],
       [20, 16, 24, 25],
       [30, 34, 54, 12],
       [48, 17, 17, 31]])

In [208]:
arr = np.random.randint(5,60,(3,3))
arr

array([[22, 55, 42],
       [38, 35, 44],
       [17, 23, 31]])

In [209]:
arr.reshape(9)

array([22, 55, 42, 38, 35, 44, 17, 23, 31])

In [210]:
arr.reshape(3,3,1)

array([[[22],
        [55],
        [42]],

       [[38],
        [35],
        [44]],

       [[17],
        [23],
        [31]]])

In [211]:
arr.reshape(3,-1)

array([[22, 55, 42],
       [38, 35, 44],
       [17, 23, 31]])

In [212]:
arr.max()

55

In [213]:
arr.min()

17

In [214]:
import numpy as np

In [215]:
arr = np.random.randint(1,100,(5,5))
arr

array([[49, 29, 16,  3, 32],
       [44, 46, 85, 72, 21],
       [80, 72, 11, 52, 65],
       [ 1, 41,  2, 58,  6],
       [42, 19, 93, 34, 33]])

In [216]:
arr.max()

93

In [217]:
arr.reshape(3,25)

ValueError: cannot reshape array of size 25 into shape (3,25)

In [218]:
arr[3:,3:]  # first is row and the second is column

array([[58,  6],
       [34, 33]])

In [219]:
arr[:,[1,3]]

array([[29,  3],
       [46, 72],
       [72, 52],
       [41, 58],
       [19, 34]])

In [220]:
arr[:,[1,2]]

array([[29, 16],
       [46, 85],
       [72, 11],
       [41,  2],
       [19, 93]])

In [221]:
arr = np.random.randint(1,100,(5,5))
arr

array([[74, 21, 51, 31, 24],
       [58, 23, 36, 84, 19],
       [85, 27, 38, 51, 68],
       [74, 35,  3, 25,  4],
       [ 5, 44, 48, 41, 91]])

In [222]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True, False],
       [False,  True,  True,  True,  True]])

In [223]:
arr1 = np.random.randint(1,10,(3,3)) 

In [224]:
arr1

array([[8, 1, 3],
       [5, 3, 9],
       [9, 4, 1]])

In [225]:
arr2 = np.random.randint(1,20,(3,3))
arr2                         

array([[11,  9, 19],
       [ 3, 13, 11],
       [12,  1,  2]])

In [226]:
arr1*arr2

array([[ 88,   9,  57],
       [ 15,  39,  99],
       [108,   4,   2]])

In [227]:
arr1@arr2  # this is a matrix multiplation

array([[127,  88, 169],
       [172,  93, 146],
       [123, 134, 217]])

In [228]:
arr**2

array([[5476,  441, 2601,  961,  576],
       [3364,  529, 1296, 7056,  361],
       [7225,  729, 1444, 2601, 4624],
       [5476, 1225,    9,  625,   16],
       [  25, 1936, 2304, 1681, 8281]], dtype=int32)

In [229]:
arr/0

C:\Users\SHAHRU~1\AppData\Local\Temp/ipykernel_10808/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [230]:
# concept call as broad castiong
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [231]:
arr = np.array([1,2,3,4])

In [232]:
arr

array([1, 2, 3, 4])

In [233]:
ar = np.array([1,2])
ar

array([1, 2])

In [234]:
arr2 +arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [235]:
ar1 = np.array([[1,2,3]])   # change in to 2d

In [236]:
ar1

array([[1, 2, 3]])

In [237]:
ar1.reshape(3,1,)+arr

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [238]:
ar1.T + arr

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [239]:
np.sqrt.array(1,2,3)

AttributeError: 'numpy.ufunc' object has no attribute 'array'

In [240]:
a = np.random.rand(5,4)
a

array([[0.61007133, 0.79375465, 0.93471411, 0.85259225],
       [0.11925018, 0.27224536, 0.86107575, 0.96886867],
       [0.39914512, 0.9019295 , 0.34891124, 0.2737483 ],
       [0.79696408, 0.60766003, 0.13087708, 0.82513929],
       [0.86410707, 0.03227123, 0.23852678, 0.15636447]])

In [241]:
np.sqrt(a)

array([[0.78107063, 0.89092909, 0.96680614, 0.92335922],
       [0.34532619, 0.52177137, 0.92794167, 0.98431127],
       [0.63177933, 0.94969969, 0.59068709, 0.52320962],
       [0.89272845, 0.77952552, 0.36176937, 0.90837178],
       [0.9295736 , 0.17964194, 0.48839204, 0.39542948]])

In [242]:
np.log10(a)

array([[-0.21461939, -0.10031372, -0.0293212 , -0.06925862],
       [-0.92354096, -0.56503951, -0.06495864, -0.01373509],
       [-0.39886917, -0.04482741, -0.45728504, -0.56264856],
       [-0.09856125, -0.21633933, -0.88313642, -0.08347273],
       [-0.06343244, -1.49118454, -0.62246285, -0.80586191]])

In [243]:
np.exp(a)

array([[1.84056268, 2.21168496, 2.54648534, 2.34571967],
       [1.12665175, 1.3129091 , 2.36570422, 2.63496176],
       [1.49054991, 2.46435351, 1.41752336, 1.31488381],
       [2.21879461, 1.83612988, 1.13982766, 2.28219862],
       [2.37288633, 1.03279759, 1.2693777 , 1.16925229]])

In [244]:
np.random.seed(20) # if we are using this so data noty be change over here
np.random.rand(2,4)  # every time data is change

array([[0.5881308 , 0.89771373, 0.89153073, 0.81583748],
       [0.03588959, 0.69175758, 0.37868094, 0.51851095]])